# fly.toml app configuration file generated for pcqa on 2023-06-01T11:10:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pcqa"
primary_region = "lhr"

[env]
  PORT = "3000"
  ORIGIN = "https://pcqa.fly.dev/"
  DB_PATH = "/data/pcqa_data/questions.sqlite3"

# add a volume for our sqlite db
[mounts]
  source="pcqa_data"
  destination="/data"

[experimental]
  cmd = "start.sh"
  entrypoint = "sh"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
